# 使用 CircleCI 流水线处理引擎的最新 2.1 版本。
version: 2.1

jobs:
  build-and-run:
    # 指定执行器类型
    docker:
      - image: cimg/base:current # 指定要使用的 Docker 镜像
    
    # 在这里为 Docker 执行器指定资源大小
    resource_class: large # <-- 将 resource_class 放在这里，与 docker 平级

    steps:
      - checkout
      - run:
          name: "查看当前目录"
          command: |
            sudo ls -la
            sudo pwd
      - run:
          name: "解压并运行 go-cve-directory"
          command: |
            tar -xzvf go-cve-dictionary_0.13.1_linux_amd64.tar.gz
            ls -la
            ./go-cve-directory --help

workflows:
  build-and-run-workflow:
    jobs:
      - build-and-run
