# 使用 CircleCI 流水线处理引擎的最新 2.1 版本。
version: 2.1

jobs:
  build-and-run:
    # 指定执行器类型
    docker:
      - image: cimg/base:current
    
    # 在这里为 Docker 执行器指定资源大小
    resource_class: large 

    steps:
      - checkout
      - run:
          name: "解压 go-cve-dictionary"
          command: |
            tar -xzvf go-cve-dictionary_0.13.1_linux_amd64.tar.gz
      - run:
          name: "爬取 NVD 漏洞信息"
          command: "./go-cve-dictionary fetch nvd --dbpath=$PWD/nvd.sqlite3"
      - run:
        name: "创建nvd制品目录"
        command: |
          mkdir /tmp/nvd-artifacts
          cp nvd.sqlite3 /tmp/nvd-artifacts/
      - store_artifacts:
          path: /tmp/nvd-artifacts
          destination: nvd.sqlite3
workflows:
  build-and-run-workflow:
    jobs:
      - build-and-run
